task_repo_and_test
tomOsuch/library pull request #2
Opened 2020-11-28 13:57 UTC by tomOsuch

Utworzone interfejsy `Repository` oraz wstępne testy do nich. 

- Jednak mam problem z klasą testową `RentRepositoryTestSuite` a dokładnie w niej z testem `testRentSaveDbWithBook()` - wychodzi niestety NullPointerException

2020-11-28 22:59 UTC, marszelun commented
> Utworzone interfejsy `Repository` oraz wstępne testy do nich.
> 
> * Jednak mam problem z klasą testową `RentRepositoryTestSuite` a dokładnie w niej z testem `testRentSaveDbWithBook()` - wychodzi niestety NullPointerException

Prawdopodobnie dzieje się tak, ponieważ nie zapisujesz do bazy książki. Dobrze mieć zapisaną książkę, zanim ją wypożyczysz ;)

2020-11-29 13:26 UTC, tomOsuch commented
Ok z Tym już sobie poradziłem :). To teraz drugie pytanie czy nie powinno być jeszcze modyfikacja w modelu danych np. w Encji `Book` nie powinno występować jeszcze pole typu `String isbn` a w encji `Rent` pole `serialNumber`. Chodzi mi tutaj o identyfikację sam nr ID jest nadawany w locie i jest chociażby mało test-owalny

2020-11-30 16:27 UTC, marszelun requested changes
Szczegółowe komentarze co do isbn i serialNumber zostawiłem przy kodzie. Tu jeszcze pytanie ogólne: co masz na myśli mówiąc, że ID nadawany w locie jest mało testowalny?
We wszystkich asercjach w teście możesz oprzeć się o id wzięty z obiektu zwróconego z metody save (on jest wzbogacony o nadany id).

2020-11-30 16:27 UTC, marszelun commented on src/main/java/com/kodilla/library/model/Book.java
> +    private String isbn;
ISBN powinien dotyczyć `Title`, nie `Book`.

2020-11-30 16:27 UTC, marszelun commented on src/main/java/com/kodilla/library/model/Rent.java
> +    private String serialNumber;
Moim zdaniem to pole jest zupełnie zbędne, po to masz unikalne id wypożyczenia, aby pełniło tę rolę.
Uwaga, automatycznie generowany id niekoniecznie musi być liczbą, można użyć np. UUID (do wygooglowania co to oraz jak to połączyć z Hibernatem i MySQL-em).

2021-02-04 01:25 UTC, merged